# Generated by Django 2.2.3 on 2020-04-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0024_auto_20200402_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookID',
        ),
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
