# Generated by Django 2.2.3 on 2020-04-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0025_auto_20200403_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='bookID',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
    ]
