# Generated by Django 2.2.3 on 2020-04-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0027_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='id',
        ),
        migrations.AddField(
            model_name='listing',
            name='listingID',
            field=models.AutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='bookID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradebooks.Book'),
        ),
    ]
