# Generated by Django 2.2.3 on 2020-04-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0027_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookID',
        ),
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradebooks.Book'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default='7GHyVB', unique=True),
        ),
    ]
