# Generated by Django 2.2.3 on 2020-04-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0027_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookID',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='book',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='book_bought',
        ),
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
