# Generated by Django 2.2.3 on 2020-04-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0028_auto_20200404_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='bookID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='book',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='book_bought',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_bought', to='tradebooks.Book'),
        ),
    ]
