# Generated by Django 2.2.3 on 2020-04-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0028_auto_20200404_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default='jYasdI', unique=True),
        ),
    ]
