# Generated by Django 2.2.3 on 2020-04-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0029_auto_20200404_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listingID',
        ),
        migrations.AddField(
            model_name='listing',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
