# Generated by Django 2.2.3 on 2020-04-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0029_listing_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='bookID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
