# Generated by Django 2.2.3 on 2020-04-04 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0030_auto_20200404_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tradebooks.Book'),
            preserve_default=False,
        ),
    ]
