# Generated by Django 2.2.3 on 2020-04-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0031_remove_listing_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tradebooks.Book'),
            preserve_default=False,
        ),
    ]
