# Generated by Django 2.2.3 on 2020-04-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0032_auto_20200404_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='bookID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
