# Generated by Django 2.2.3 on 2020-04-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0033_auto_20200404_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='book',
        ),
    ]
