# Generated by Django 2.2.3 on 2020-03-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courseMain',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='studentID',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
