# Generated by Django 2.2.3 on 2020-04-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0002_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
