# Generated by Django 2.2.3 on 2020-03-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0005_userprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='studentID',
            field=models.CharField(blank=True, max_length=30, primary_key=True, serialize=False),
        ),
    ]
