# Generated by Django 2.2.3 on 2020-03-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0009_auto_20200320_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='payID',
        ),
        migrations.AddField(
            model_name='payment',
            name='book_bought',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_bought', to='tradebooks.Book'),
        ),
    ]
