# Generated by Django 2.2.3 on 2020-03-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0010_auto_20200320_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookBought',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_buyers', to='tradebooks.UserProfile'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookSold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_sellers', to='tradebooks.UserProfile'),
        ),
    ]
