# Generated by Django 2.2.3 on 2020-04-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0024_auto_20200402_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookID',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
    ]
