# Generated by Django 2.2.3 on 2020-04-04 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookISBN', models.CharField(blank=True, max_length=120)),
                ('bookName', models.CharField(max_length=100)),
                ('bookImage', models.ImageField(blank=True, upload_to='book_images')),
                ('bookAuthor', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=30)),
                ('year', models.IntegerField(default=1)),
                ('bookDescription', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('currency', models.CharField(blank=True, default='GBP', max_length=3)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('studentID', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
                ('courseMain', models.CharField(blank=True, max_length=30)),
                ('year', models.IntegerField(default=1)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=128, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('processed', models.BooleanField(default=False)),
                ('book_bought', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_bought', to='tradebooks.Book')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_payee', to='tradebooks.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, default='', max_length=3000)),
                ('slug', models.SlugField(default='', unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradebooks.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradebooks.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='bookBought',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_buyers', to='tradebooks.UserProfile'),
        ),
        migrations.AddField(
            model_name='book',
            name='bookSold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_sellers', to='tradebooks.UserProfile'),
        ),
    ]
