# Generated by Django 2.2.3 on 2020-03-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0002_auto_20200319_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='time',
        ),
    ]
