# Generated by Django 2.2.3 on 2020-03-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0003_auto_20200319_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='time',
            new_name='user',
        ),
    ]
