# Generated by Django 2.2.3 on 2020-03-20 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0006_auto_20200320_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookISBN', models.CharField(blank=True, max_length=120)),
                ('bookID', models.IntegerField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=100)),
                ('bookImage', models.ImageField(blank=True, upload_to='profile_images')),
                ('bookAuthor', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=30)),
                ('year', models.IntegerField(default=1)),
                ('bookDescription', models.CharField(max_length=100)),
                ('bookBought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_buyers', to='tradebooks.UserProfile')),
                ('bookSold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_sellers', to='tradebooks.UserProfile')),
            ],
        ),
    ]
