# Generated by Django 2.2.3 on 2020-03-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0011_auto_20200320_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='currency',
            field=models.CharField(blank=True, default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
