# Generated by Django 2.2.3 on 2020-03-31 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0012_auto_20200328_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'books'},
        ),
    ]
