# Generated by Django 2.2.3 on 2020-03-31 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0013_auto_20200401_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
