# Generated by Django 2.2.3 on 2020-04-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradebooks', '0020_listing_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='slug',
        ),
    ]
